### ISSUE TITLE
error：RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

### ISSUE THREAD

**Issue by lipeng1109** [Isi-dev/ComfyUI-UniAnimate-W#23]
full error:

Unrecognized args: []
Ready for inference.
libuv is not supported, disabling USE_LIBUV
Running UniAnimate inference on gpu (0)
Loaded ViT-H-14 model config.
Loading pretrained ViT-H-14 weights (/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/checkpoints/open_clip_pytorch_model.bin).
!!! Exception during processing !!! The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
Traceback (most recent call last):
  File "/data/aigc/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/aigc/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/aigc/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data/aigc/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/uniAnimate_Inference.py", line 49, in process
    frames = inference_unianimate_entrance(seed, steps, useFirstFrame, reference_image, ref_pose, pose_sequence, frame_interval, max_frames, resolution, cfg_update=cfg_update.cfg_dict)
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/tools/inferences/inference_unianimate_entrance.py", line 73, in inference_unianimate_entrance
    return worker(0, seed, steps, useFirstFrame, reference_image, ref_pose, pose_sequence, frame_interval, max_frames, resolution, cfg, cfg_update)
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/tools/inferences/inference_unianimate_entrance.py", line 274, in worker
    _, _, zero_y = clip_encoder(text="")
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/tools/modules/clip_embedder.py", line 212, in forward
    xt, x = self.encode_with_transformer(tokens.to(self.device))
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/tools/modules/clip_embedder.py", line 219, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-UniAnimate-W/tools/modules/clip_embedder.py", line 236, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 6131, in multi_head_attention_forward
    raise RuntimeError(
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

**Comment by Isi-dev** [comment]
You can try navigating to /data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/open_clip/transformer.py and change on line 329: batch_first: bool = True, to batch_first: bool = False.

**Comment by lipeng1109** [comment]
> You can try navigating to /data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/open_clip/transformer.py and change on line 329: batch_first: bool = True, to batch_first: bool = False.

Thanks, I'll try it; I solved it by installing pip install open-clip-torch==2.24.0

**Comment by Isi-dev** [comment]
> > You can try navigating to /data/aigc/ComfyUI/.venv/lib/python3.10/site-packages/open_clip/transformer.py and change on line 329: batch_first: bool = True, to batch_first: bool = False.
> 
> Thanks, I'll try it; I solved it by installing pip install open-clip-torch==2.24.0

This should also work because this version of open_clip does not include the 'batch_first: bool = True' parameter
